def create(indexes):
    res = [[0]*8 for _ in range(len("ACGT"))]
    print(res)
    seqs = [
    "ATATAGTGCTAGATCTGATCGATGCTAAATGCTAGATAGTGATCGTAGAGCTGATAGCGTAGATATAGATGCGCTGCTAGAATGCTGATAGCTGAAATAGATCGATAGTCGATAGTCGCTGATAGTCTGTAGCTGATGCGCTGATGGATGTTTGGGTACACGATGCTGATACGCATGATGATGATGAACA",
    "ATATAGTCTAATCTGATCGCATGCTAATGCGTAGATAGTGATCGTAGAGTGATAGCGTAGGATATAATGCGCTGCTAGAATCTGATAAGCTGAAATAGATCGATAGTCATAGTCGCTGATAGTCTGTAAGTGATGCGCGATGGATGTTTGGTACTACGATGCTATAGCTCGAGATCGAAGCGATGCT",
    "ATAAATAGTGCTAGATCTGATCACTCGTCGTCGCTAGATAGTGATTCGTAGAGCTGATAGCGTAGATATAGATGCGCTGCTAGAATGCTGATAGCTGAAATACTCGCGATGCTGCTGATAGTCTGTAGCTGATGCGCTGATGGATGTTTGGGTACACGATGCTGACTGCGATATGAGATCGATAGCG",
    "ATAGCTCGATGCTTAGATCTCGCGTATGCTGCTAGATAAGAGCTGCTGAGCTGATCGGATGCCTCGCGCTCGCGCGCTGAGGCTCGGATAGCTAGCTGAGCGCTCGATAGCGCGTTCGCTGGATCGCGTATAGCGCTGAAGCTCCCGGCTAGCTGTCTGTAAATCGGATCTGATCTCGCTCTATACT",
    "CGACGACGACGACGAATGATGATGATGACCGCCGTAGAGCTAGCTGAGCTGCTTAGCTGATCGCGATATGAGAGAGAGCTATAGAGCTTTTTTTTTTTTGGGGGGGGGGGGGAAAAAAAAAAAGGGGGGGGATAGAGATAGCTGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    ]
    for i,idx in enumerate(indexes):
        subseq = seqs[i][idx:(idx + 8)]
        for ms in range(8):
            for k in range(len( "ACGT" )):
                if subseq[ms] == "ACGT"[k]:
                    res[k][ms] = res[k][ms] + 1
    return res
    
idxs= create([25,20,2,55,59])
print(idxs)
